# Generated by Django 2.2.5 on 2019-09-21 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_auto_20190918_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField()),
                ('returndate', models.DateField()),
                ('fine', models.IntegerField()),
                ('BookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.Book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
