# Generated by Django 2.2.5 on 2019-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='issuedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
