# Generated by Django 2.2.5 on 2019-09-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0004_auto_20190921_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='issuedate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
